[workspace]

resolver = "2"
members = [
    "common",
    "day01_1",
    "day01_2",
    "day01_lib",
    "day02_1",
    "day02_2",
    "day02_lib",
    "day03_1",
    "day03_2",
    "day03_lib",
    "day04_1",
    "day04_lib",
]
